### ISSUE TITLE
Resolve parser errors

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-neon#67]
```neon
services:
    app.admin.login.factory:
        implement: App\Admin\Login\Control\Login\LoginControlFactory
        arguments:
            ###
            # Warning: Service 'ori' not found
            #   Ignoruje část za tečkou
            ###
            authorizer: @ori.ui.auth.authorizer
decorator:
    OriCMF\UI\Presenter\Base\BasePresenter:
        setup:
            ###
            # Warning: Service 'self' not found
            #   Odkaz na aktuální službu
            ###
            - "?['document-head-icons']->setFavicon('/images/favicon.ico')" = @self
localization:
    loaders:
        ###
        # Error: bad indent
        #   Jesliže klíč a první položka pole jsou na stejném řádku,
        #   tak je možné odsadit následující položky s mezerou pro zarovnání ačkoli jsou řádky odsazené tabem
        ###
        - factory: Orisai\Localization\Resource\FileLoader
          arguments:
            directories: [%appDir%/**/translations/**]
###
# Nefunguje reference na třídu, kvůli erroru výš v souboru
###
example: Orisai\Localization\Resource\FileLoader
```

**Comment by mabar** [comment]
Found another bug example thanks to https://ne-on.org

For following neon are reported "Duplicate key" errors which seem to be related to combination of whitespace in key and non-unique parts between spaces (e.g. `bool` and `bool_alternative`)

```
special types:
	escape sequences: "\u2026 \t \n \r \f \b"
	bool: [true, false]
	bool alternative: [yes, no]
	exponent number: +0123.45e6
	hex number: 0xAB01
	octal number: 0o666
	binary number: 0b11100111
	date: 2020-02-02
	date time: 2020-02-02 12:34:56

```

But changing the code results into some really strange behavior:

Base:
![base](https://user-images.githubusercontent.com/20974277/123560894-72c4ae00-d7a5-11eb-84f0-71cd885c4cb5.PNG)

With removal of `escape sequences`, error from `bool alternative` disappered:
![escape_sequence](https://user-images.githubusercontent.com/20974277/123560905-840dba80-d7a5-11eb-88db-aa79b27a2c87.PNG)

Change from `bool alternative` to `something unique` didn't help, still reports on the line:
![something_unique](https://user-images.githubusercontent.com/20974277/123560915-8c65f580-d7a5-11eb-9611-8e978f2006bb.PNG)

**Comment by mabar** [comment]
Comma after last entity attribute is valid neon, but reports `Empty element parsed in 'mainArray_0' at offset 679` on `(` and `<value> or '[Neon] NEON_INDENT' expected, got ')'` on `)`
```neon
# Works
- App\Front\AppFrontMenuProvider(
	@OriCMF\UI\Front\Auth\FrontFirewall,
	@App\Core\Client\ClientRepository
)

# Reports error, but shouldn't
- App\Front\AppFrontMenuProvider(
	@OriCMF\UI\Front\Auth\FrontFirewall,
	@App\Core\Client\ClientRepository,
)
```

**Comment by mabar** [comment]
Some more examples - take a look at names of keys in different levels and tabs/spaces on the last line

```
monolog:
    channels:
        <name>:
            handlers:
            processors:
    handlers:
        <name>: []
```

![a](https://user-images.githubusercontent.com/20974277/128487443-1e598e2a-ddab-4a58-9401-a274e079a08b.PNG)
![b](https://user-images.githubusercontent.com/20974277/128487447-2e373dd4-e5c8-4b57-9aed-d1b8a07ab7b9.PNG)
![c](https://user-images.githubusercontent.com/20974277/128487448-6e10196d-7f8c-4515-8523-acb8da5df83f.PNG)
![f](https://user-images.githubusercontent.com/20974277/128487455-2a48e444-994b-40c3-b876-b188833a5ef9.PNG)
![d](https://user-images.githubusercontent.com/20974277/128487449-b07f99ac-3a39-463a-bd79-f482dd9a4926.PNG)
![e](https://user-images.githubusercontent.com/20974277/128487453-afa0a134-f000-4500-864a-18e368543634.PNG)

**Comment by mesour** [comment]
@mabar I tried fix problem with:

```
        ###
        # Error: bad indent
        #   Jesliže klíč a první položka pole jsou na stejném řádku,
        #   tak je možné odsadit následující položky s mezerou pro zarovnání ačkoli jsou řádky odsazené tabem
        ###
        - factory: Orisai\Localization\Resource\FileLoader
          arguments:
```

And it is not simply as I thought. Maybe it will be marked as a known limitation.

**Comment by mesour** [comment]
Experimental version is closed and replaced with new https://plugins.jetbrains.com/plugin/18387-neon-nette-support plugin
