### ISSUE TITLE
Closing Project dialog is shown for 30+seconds with Neon plugin enabled

### ISSUE THREAD

**Issue by PhilETaylor** [nette-intellij/intellij-neon#74]
**Describe the bug**
When switching projects or closing phpStorm the Closing Project dialog is shown for 30+ seconds and hangs the process

<img width="497" alt="ScreenShot-2023-04-06-18 09 11" src="https://user-images.githubusercontent.com/400092/230453415-5a3ac167-a1bf-4a58-bc7b-cffc2028d426.png">

**Environment (please complete the following information):**
 - PhpStorm 2023.1
 - 0.5.3 updated today

**To Reproduce**
Steps to reproduce the behavior (or attach video):
1. Open a project
2. Switch to another project using cmd+o and select project - or just quit phpStorm
3. See that the closing dialog shows for a very very long time

**Additional context**
Disabling the Neon plugin fixes the problem

**Comment by honzavaclavik** [comment]
Same problem here

**Comment by honzavaclavik** [comment]
@mesour Any update?

**Comment by mesour** [comment]
I found the problem. I will make new version until the end of the week at most.

**Comment by honzavaclavik** [comment]
Please fix it 😇

**Comment by mesour** [comment]
@badpenguin yes. Sorry, I didn't have time for that. I keep it in my mind.

**Comment by mesour** [comment]
Fixed in 0.5.4 it will be available in 2 business days

**Comment by honzavaclavik** [comment]
0.5.4 Works for me, thanks
